### ISSUE TITLE
Картинки для прикроватных светильников

### ISSUE THREAD

**Issue by fsa** [Gelezako/MajorDomo-Yeelight#3]
Отсутствуют картинки bslamp, bslamp1 (у меня такое устройство определилось). Внешне он выглядит так: https://www.yeelight.com/en_US/product/cherry1s

**Comment by fsa** [comment]
![bslamp](https://user-images.githubusercontent.com/1696211/40931821-a8897ec4-6856-11e8-9227-0eb5879c4031.png)
![bslamp1](https://user-images.githubusercontent.com/1696211/40931824-ad79c4a2-6856-11e8-8976-cf239af951c2.png)
Для примера преобразованный ресурс из приложения Yeelight (установлен размер 96х96).

**Comment by Gelezako** [comment]
я уже залил другие, посмотрите как будет смотреться. Если плохо, то закину ваши.

**Comment by fsa** [comment]
Нет. Спасибо. Просто сделал, чтобы не заморачиваться с поиском. Всё отлично выглядит.
