### ISSUE TITLE
Цикл обнаружения устройств никогда не запустится, устройства обнаруживаются нестабильно

### ISSUE THREAD

**Issue by fsa** [Gelezako/MajorDomo-Yeelight#5]
Из-за блока кода
>$tmp = SQLSelectOne("SELECT ID FROM  LIMIT 1");
>if (!$tmp['ID'])
>   exit; // no devices added -- no need to run this cycle

цикл никогда не запустится. Запрос ошибочный и всегда вернётся пустой ответ. Следующее условие просто заставляет цикл завершиться.
Я тоже пытался реализовать модуль, но так пока его и не доделал https://github.com/fsa/majordomo-yeelight В нём уже реализовано обнаружение устройств и создание записей об устройствах в отдельной таблице в базе данных, но эту логику можно изменить легко. Часть кода сделана по аналогии с xiaomihome.
По идее нужно отправить запрос sddp:discovery, после чего ждать ответа от устройств. При обнаружении ответа нужно его отправить веб-серверу для обработки и манипуляции с данными Majordomo.

**Comment by Gelezako** [comment]
на самом деле я не реализовывал работу цикла т.к. пока толком не понимаю как работает эта архитектура. Файл cycle_Yeelight.php положил для будущих реализаций, я в курсе что он пустой. Что бы устройства обнаружились цикл не надо запускать.
